[package]
name = "rust-lstm-1025"
version = "0.1.1"
edition = "2024"

description = "A Rust implementation of a BMI (Basic Model Interface) adapter for LSTM-based streamflow prediction."
readme = "./README.md"
authors = ["Josh Cunningham <jcunningham8@ua.edu>"]
license = "MIT"

homepage = "https://github.com/CIROH-UA/rust-lstm"
repository = "https://github.com/CIROH-UA/rust-lstm"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
bmi-rs = "0.0.1-alpha.0"
burn = { version = "0.18.0", features = ["candle", "ndarray"] }
burn-import = "0.18.0"
ffi = {package = "bmi-rs-sys", version = "0.0.1" }
glob = "0.3.3"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
